---
title: "701_Milfersk2023_pooled_samples"
format: html
---

## Packages  

```{r}

library(dplyr)
library(purrr)
library(lubridate)
library(readxl)
library(ggplot2)
library(tidyr)

source("701_Milfersk2023_pooled_samples_functions.R")

```


## Data  

```{r}

dat_orig1 <- read.csv("Milfersk/Data_combined/001 MF Mjøsa  stack.txt")

# xtabs(~Label, dat_orig1)
xtabs(~Label, dat_orig1 %>% filter(grepl("138", Label)))

# Add substamce names (Identifier) and area, species, tissue, year
lookup_label <- read.csv("Milfersk/Data_combined/002 Combined Compounds.txt")
lookup_sample <- read.csv("Milfersk/Data_combined/003 MF samples.txt")

dat_orig2 <- dat_orig1 %>%
  left_join(lookup_label %>% select(Label, Identifier, Group, Subgroup),
            by = join_by(Label)) %>%
  left_join(lookup_sample %>% select(LIMS.NR, MYEAR, Compartment, Area, Species.2, Tissue, Weight..g., Length..cm. ),
            by = join_by(LIMS.NR))

if (nrow(dat_orig2) > nrow(dat_orig1))
  stop("Check data - left join increased no. of rows")

table(addNA(lookup_sample$Area))
table(addNA(dat_orig2$MYEAR))
table(addNA(dat_orig2$Area))
table(addNA(dat_orig2$Species.2))
xtabs(~addNA(Species.2) + addNA(Tissue), dat_orig2)
xtabs(~addNA(MYEAR), dat_orig2)
xtabs(~addNA(Tissue) + addNA(MYEAR), dat_orig2 %>% filter(Species.2 %in% c("Brown trout", "Abbor -muskel")))

# Extract year - TEST
x <- stringr::str_extract(dat_orig2$LIMS.NR, "20[1-2][0-9]")
table(x)

xtabs(~addNA(LOQ == 1) + addNA(MYEAR), 
      dat_orig2 %>% filter(Species.2 %in% c("Brown trout", "Abbor -muskel")))

xtabs(~addNA(Data.availability) + addNA(MYEAR), 
      dat_orig2 %>% filter(Species.2 %in% c("Brown trout", "Abbor -muskel")))
xtabs(~Identifier + addNA(Data.availability), 
      dat_orig2 %>% filter(Species.2 %in% c("Brown trout", "Abbor -muskel")))

xtabs(~addNA(Data.availability) + addNA(MYEAR), 
      dat_orig2)


dat <- dat_orig2 %>%
  mutate(
    Year = as.numeric(stringr::str_extract(LIMS.NR, "20[1-2][0-9]")),
    LATIN_NAME = case_when(
      Species.2 %in% c("Brown trout", "Abbor -muskel") ~ "Brown trout",
      TRUE ~ Species.2),
    FLAG1 = case_when(
      Data.availability %in% 0 ~ "<",
      Data.availability %in% 1 ~ as.character(NA))
  ) %>%
  rename(
    NAME = Identifier,
    STATION_NAME = Area,
    TISSUE_NAME = Tissue,
    SAMPLE_ID = LIMS.NR,
    VALUE = UB
    ) %>%
  select(-Species.2)

xtabs(~addNA(MYEAR) + addNA(Year), dat)
xtabs(~addNA(LATIN_NAME) + addNA(Year), dat)
xtabs(~addNA(TISSUE_NAME) + addNA(Year), dat %>% filter(LATIN_NAME %in% "Brown trout"))


```

## Testing  

### Make data from random draws  

```{r}

test <- get_combined_data(c("PFOSA", "PFOS"), 
                    "Brown trout", "Mjøsa", "Muscle", 2018, 
                    no_samples = 4, no_draws = 2, 
                    data = dat)

# test
ggplot(test, aes(Sampling, Conc)) +
  geom_point(aes(shape = `LOQ status`)) +
  scale_shape_manual(values = c("Over LOQ" = 16, "Under LOQ" = 6)) +
  facet_wrap(vars(NAME), scales = "free_y")

```

### As above, but for several years  

```{r}

all_yrs <- dat %>% 
  filter(LATIN_NAME %in% "Brown trout" & TISSUE_NAME %in% "Muscle") %>%
  pull(Year) %>%
  unique()

test <- map(all_yrs,
            \(year) get_combined_data(c("BDE99", "PFOS"), 
                    "Brown trout", "Mjøsa", "Muscle", year = year, 
                    no_samples = 4, no_draws = 2, 
                    data = dat)) %>%
  list_rbind()

# test
ggplot(test, aes(Year, Conc, color = Sampling)) +
  geom_point(aes(shape = `LOQ status`)) +
  scale_shape_manual(values = c("Over LOQ" = 16, "Under LOQ" = 6)) +
  facet_grid(vars(NAME), vars(Sampling), scales = "free_y")


```



